/* Generated By:JavaCC: Do not edit this line. textConstants.java */
package compiladordibujos;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface textConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 1;
  /** RegularExpression Id. */
  int CABECERA = 2;
  /** RegularExpression Id. */
  int RECTANGULO = 3;
  /** RegularExpression Id. */
  int CIRCULO = 4;
  /** RegularExpression Id. */
  int LINEA = 5;
  /** RegularExpression Id. */
  int TEXTO = 6;
  /** RegularExpression Id. */
  int ALTO = 7;
  /** RegularExpression Id. */
  int ANCHO = 8;
  /** RegularExpression Id. */
  int COLOR = 9;
  /** RegularExpression Id. */
  int POSICION = 10;
  /** RegularExpression Id. */
  int RADIO = 11;
  /** RegularExpression Id. */
  int FONDO = 12;
  /** RegularExpression Id. */
  int TIPO = 13;
  /** RegularExpression Id. */
  int FUENTE = 14;
  /** RegularExpression Id. */
  int TAM = 15;
  /** RegularExpression Id. */
  int ABREETI = 16;
  /** RegularExpression Id. */
  int CIERRAETI = 17;
  /** RegularExpression Id. */
  int CIERRA = 18;
  /** RegularExpression Id. */
  int POSX = 19;
  /** RegularExpression Id. */
  int POSY = 20;
  /** RegularExpression Id. */
  int POSX2 = 21;
  /** RegularExpression Id. */
  int POSY2 = 22;
  /** RegularExpression Id. */
  int NUMBER = 23;
  /** RegularExpression Id. */
  int TEXT = 24;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"dibujo\"",
    "\"cabecera\"",
    "\"rectangulo\"",
    "\"circulo\"",
    "\"linea\"",
    "\"texto\"",
    "\"alto\"",
    "\"ancho\"",
    "\"color\"",
    "\"posicion\"",
    "\"radio\"",
    "\"fondo\"",
    "\"tipo\"",
    "\"fuente\"",
    "\"tam\"",
    "\"<\"",
    "\">\"",
    "\"/\"",
    "\":x\"",
    "\":y\"",
    "\":x2\"",
    "\":y2\"",
    "<NUMBER>",
    "<TEXT>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
  };

}
